version: '3.5'
services: 
  discord-bot:
    build: .
    command: npm run start
    volumes: 
      - .:/usr/app/
      - ./node_modules/:/usr/app/node_modules
    env_file: 
      - .env
    restart: always
